---

- name: Load bridge netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present

- name: Enable IPv4 Forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: Enable bridge netfiltering
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: true
    state: present
    reload: true

